export const LOAD_PRODUCTS_FROM_CART = 'loadProductsFromCart'
export const ADD_PRODUCT_TO_CART = 'addProductToCart'
export const SET_CART_ID = 'setCartId'
export const DELETE_PRODUCT_FROM_CART = 'deleteProductsFromCart'
export const FINISH_PURCHASE = 'finishPurchase'
